-- ============================================================================
-- Seed: ISO 3166-1 country names → alpha-2 codes
-- Idempotent: MERGE ensures rows are inserted or updated safely.
-- Source: ISO 3166-1 standard (249 entries)
-- ============================================================================

USE stoxx;
GO

MERGE bronze.dim_country AS tgt
USING (VALUES
    (N'Afghanistan', 'AF'),
    (N'Albania', 'AL'),
    (N'Algeria', 'DZ'),
    (N'American Samoa', 'AS'),
    (N'Andorra', 'AD'),
    (N'Angola', 'AO'),
    (N'Anguilla', 'AI'),
    (N'Antarctica', 'AQ'),
    (N'Antigua and Barbuda', 'AG'),
    (N'Argentina', 'AR'),
    (N'Armenia', 'AM'),
    (N'Aruba', 'AW'),
    (N'Australia', 'AU'),
    (N'Austria', 'AT'),
    (N'Azerbaijan', 'AZ'),
    (N'Bahamas', 'BS'),
    (N'Bahrain', 'BH'),
    (N'Bangladesh', 'BD'),
    (N'Barbados', 'BB'),
    (N'Belarus', 'BY'),
    (N'Belgium', 'BE'),
    (N'Belize', 'BZ'),
    (N'Benin', 'BJ'),
    (N'Bermuda', 'BM'),
    (N'Bhutan', 'BT'),
    (N'Bolivia', 'BO'),
    (N'Bosnia and Herzegovina', 'BA'),
    (N'Botswana', 'BW'),
    (N'Brazil', 'BR'),
    (N'Brunei', 'BN'),
    (N'Bulgaria', 'BG'),
    (N'Burkina Faso', 'BF'),
    (N'Burundi', 'BI'),
    (N'Cabo Verde', 'CV'),
    (N'Cambodia', 'KH'),
    (N'Cameroon', 'CM'),
    (N'Canada', 'CA'),
    (N'Cayman Islands', 'KY'),
    (N'Central African Republic', 'CF'),
    (N'Chad', 'TD'),
    (N'Chile', 'CL'),
    (N'China', 'CN'),
    (N'Colombia', 'CO'),
    (N'Comoros', 'KM'),
    (N'Congo', 'CG'),
    (N'Costa Rica', 'CR'),
    (N'Croatia', 'HR'),
    (N'Cuba', 'CU'),
    (N'Curaçao', 'CW'),
    (N'Cyprus', 'CY'),
    (N'Czech Republic', 'CZ'),
    (N'Côte d''Ivoire', 'CI'),
    (N'Democratic Republic of the Congo', 'CD'),
    (N'Denmark', 'DK'),
    (N'Djibouti', 'DJ'),
    (N'Dominica', 'DM'),
    (N'Dominican Republic', 'DO'),
    (N'Ecuador', 'EC'),
    (N'Egypt', 'EG'),
    (N'El Salvador', 'SV'),
    (N'Equatorial Guinea', 'GQ'),
    (N'Eritrea', 'ER'),
    (N'Estonia', 'EE'),
    (N'Eswatini', 'SZ'),
    (N'Ethiopia', 'ET'),
    (N'Fiji', 'FJ'),
    (N'Finland', 'FI'),
    (N'France', 'FR'),
    (N'Gabon', 'GA'),
    (N'Gambia', 'GM'),
    (N'Georgia', 'GE'),
    (N'Germany', 'DE'),
    (N'Ghana', 'GH'),
    (N'Gibraltar', 'GI'),
    (N'Greece', 'GR'),
    (N'Greenland', 'GL'),
    (N'Grenada', 'GD'),
    (N'Guam', 'GU'),
    (N'Guatemala', 'GT'),
    (N'Guernsey', 'GG'),
    (N'Guinea', 'GN'),
    (N'Guinea-Bissau', 'GW'),
    (N'Guyana', 'GY'),
    (N'Haiti', 'HT'),
    (N'Honduras', 'HN'),
    (N'Hong Kong', 'HK'),
    (N'Hungary', 'HU'),
    (N'Iceland', 'IS'),
    (N'India', 'IN'),
    (N'Indonesia', 'ID'),
    (N'Iran', 'IR'),
    (N'Iraq', 'IQ'),
    (N'Ireland', 'IE'),
    (N'Isle of Man', 'IM'),
    (N'Israel', 'IL'),
    (N'Italy', 'IT'),
    (N'Jamaica', 'JM'),
    (N'Japan', 'JP'),
    (N'Jersey', 'JE'),
    (N'Jordan', 'JO'),
    (N'Kazakhstan', 'KZ'),
    (N'Kenya', 'KE'),
    (N'Kiribati', 'KI'),
    (N'Kuwait', 'KW'),
    (N'Kyrgyzstan', 'KG'),
    (N'Laos', 'LA'),
    (N'Latvia', 'LV'),
    (N'Lebanon', 'LB'),
    (N'Lesotho', 'LS'),
    (N'Liberia', 'LR'),
    (N'Libya', 'LY'),
    (N'Liechtenstein', 'LI'),
    (N'Lithuania', 'LT'),
    (N'Luxembourg', 'LU'),
    (N'Macao', 'MO'),
    (N'Madagascar', 'MG'),
    (N'Malawi', 'MW'),
    (N'Malaysia', 'MY'),
    (N'Maldives', 'MV'),
    (N'Mali', 'ML'),
    (N'Malta', 'MT'),
    (N'Marshall Islands', 'MH'),
    (N'Mauritania', 'MR'),
    (N'Mauritius', 'MU'),
    (N'Mexico', 'MX'),
    (N'Micronesia', 'FM'),
    (N'Moldova', 'MD'),
    (N'Monaco', 'MC'),
    (N'Mongolia', 'MN'),
    (N'Montenegro', 'ME'),
    (N'Morocco', 'MA'),
    (N'Mozambique', 'MZ'),
    (N'Myanmar', 'MM'),
    (N'Namibia', 'NA'),
    (N'Nauru', 'NR'),
    (N'Nepal', 'NP'),
    (N'Netherlands', 'NL'),
    (N'New Zealand', 'NZ'),
    (N'Nicaragua', 'NI'),
    (N'Niger', 'NE'),
    (N'Nigeria', 'NG'),
    (N'North Korea', 'KP'),
    (N'North Macedonia', 'MK'),
    (N'Norway', 'NO'),
    (N'Oman', 'OM'),
    (N'Pakistan', 'PK'),
    (N'Palau', 'PW'),
    (N'Palestine', 'PS'),
    (N'Panama', 'PA'),
    (N'Papua New Guinea', 'PG'),
    (N'Paraguay', 'PY'),
    (N'Peru', 'PE'),
    (N'Philippines', 'PH'),
    (N'Poland', 'PL'),
    (N'Portugal', 'PT'),
    (N'Puerto Rico', 'PR'),
    (N'Qatar', 'QA'),
    (N'Romania', 'RO'),
    (N'Russia', 'RU'),
    (N'Rwanda', 'RW'),
    (N'Saint Kitts and Nevis', 'KN'),
    (N'Saint Lucia', 'LC'),
    (N'Saint Vincent and the Grenadines', 'VC'),
    (N'Samoa', 'WS'),
    (N'San Marino', 'SM'),
    (N'Saudi Arabia', 'SA'),
    (N'Senegal', 'SN'),
    (N'Serbia', 'RS'),
    (N'Seychelles', 'SC'),
    (N'Sierra Leone', 'SL'),
    (N'Singapore', 'SG'),
    (N'Slovakia', 'SK'),
    (N'Slovenia', 'SI'),
    (N'Solomon Islands', 'SB'),
    (N'Somalia', 'SO'),
    (N'South Africa', 'ZA'),
    (N'South Korea', 'KR'),
    (N'South Sudan', 'SS'),
    (N'Spain', 'ES'),
    (N'Sri Lanka', 'LK'),
    (N'Sudan', 'SD'),
    (N'Suriname', 'SR'),
    (N'Sweden', 'SE'),
    (N'Switzerland', 'CH'),
    (N'Syria', 'SY'),
    (N'São Tomé and Príncipe', 'ST'),
    (N'Taiwan', 'TW'),
    (N'Tajikistan', 'TJ'),
    (N'Tanzania', 'TZ'),
    (N'Thailand', 'TH'),
    (N'Timor-Leste', 'TL'),
    (N'Togo', 'TG'),
    (N'Tonga', 'TO'),
    (N'Trinidad and Tobago', 'TT'),
    (N'Tunisia', 'TN'),
    (N'Turkey', 'TR'),
    (N'Turkmenistan', 'TM'),
    (N'Tuvalu', 'TV'),
    (N'Uganda', 'UG'),
    (N'Ukraine', 'UA'),
    (N'United Arab Emirates', 'AE'),
    (N'United Kingdom', 'GB'),
    (N'United States', 'US'),
    (N'Uruguay', 'UY'),
    (N'Uzbekistan', 'UZ'),
    (N'Vanuatu', 'VU'),
    (N'Vatican City', 'VA'),
    (N'Venezuela', 'VE'),
    (N'Vietnam', 'VN'),
    (N'Yemen', 'YE'),
    (N'Zambia', 'ZM'),
    (N'Zimbabwe', 'ZW')
) AS src (country_name, iso_alpha2)
ON tgt.country_name = src.country_name
WHEN MATCHED THEN UPDATE SET iso_alpha2 = src.iso_alpha2
WHEN NOT MATCHED THEN INSERT (country_name, iso_alpha2) VALUES (src.country_name, src.iso_alpha2);
GO

PRINT 'Country dimension seeded successfully.';
GO
